# Ankarafantsika

## Gestion et statut

L'ouvrage de référence sur les aires protégées terrestres malgaches coordonné par l'association Vahatra résume le cadre juridique d'Ankarafantsika de la manière suivante :

> "Aspects légaux : Gestionnaire actuel : Madagascar National Parks (MNP) ; Gestion antérieure : Direction des Eaux et Forêts (Service de la Protection de la Nature d’Antananarivo et le Service Provincial des Eaux et Forêts de Mahajanga) ; Création : selon le Décret du 31 décembre 1927 (Création de la Réserve Naturelle Intégrale n° 7) ; Modification de statut : la Réserve Naturelle Intégrale d’Ankarafantsika fut créée en 1927 et ses limites ont été précisées en 1966 avec le Décret n° 66-242 du 1 juin 1966 (60 520 ha). Parallèlement, des territoires de la Forêt d’Ankarafantsika sur les districts de Marovoay et Ambato Boeny ont été classés réserves forestières avec l’Arrêté du 24 décembre 1929 (75 000 ha). De plus, le Jardin botanique d’Ampijoroa (district d’Ambato Boeny, 91 ha), recensé en 1969 par le Domaine Forestier National est devenu la Station Forestière d’Ampijoroa (4974 ha) en 1999 par l’Arrêté interministériel n° 13-056/99 du 7 décembre 1999. En 2002, la réserve naturelle intégrale créée en 1927 et reclassée en 1966, les réserves forestières instituées en 1929 ainsi que la Station Forestière d’Ampijoroa sont toutes instituées en un seul parc national (Décret n° 2002-798 du 7 août 2002, 130 000 ha). Ce dernier subit un changement de limites en 2015 sous le Décret n° 2015-730 du 21 avril 2015 ; Dernière modification de statut : suivant le Décret n° 2015-730 du 21 avril 2015 ; Surface actuelle : 136 513 ha (selon le décret en vigueur). [@goodman2018, vol. 2, p. 157]"

### Avant 2002: 2 périmètres distincts


#### La réserve naturelle intégrale d'Ankarafantsika

Pour le périmètre RNI

> Septième réserve naturelle. — Plateau d'Ankarafantsika, situé dans le district de Marovoay, région de Majunga, superficie approximative : 66.541 hectares, ayant pour limites: Au nord, la propriété dite: « Sainte-Marie Marovoay », titre n° 784-M,dts terrains domaniaux et, à une distance de cinq kilomètres environ, les villages d'Ampombomangarakaraka et Beronono ; A l'est, des terrains domaniaux; Au sud, des terrains dumaniaux et, à quelque distance, des villages d'Ankorika et de Bevasaka ;
A l'ouest, des terrains domaniaux et la rivière Mahajamba. Tel au surplus que cette réserve naturelle est figurée à l'un des trois plans annexés audit arrêté.


Pour la la réserve forestière

> Par arrêté du Gouverneur Général p. i., en date du 24 décembre 1929, pris en conseil d'administration, est mise en réserve, dans les conditions fixées par les articles 50 à 52 du décret du 28 août 1913, la portion du massif forestier dit de l'Ankarafantsika, situé à l'ouest de la 7e réserve naturelle créée par le décret du 31 décembre 1927, dans la province de Marovoay ; La réserve ainsi instituée, d'une surface approximative de 75.000 hectares telle qu'elle est figurée au plan ci-annexé, est limitée: Au nord, par une ligne droite partant de l'angle N. W. de la 7e réserve naturelle et allant jusqu'au village d'Ampombilavakely, puis de ce village jusqu'à la limite de la propriété dite « Croix Rousse » titre n°3153; A l'ouest, par les propriété dites « Croix Rousse et Mont-rouge » titre no 3153 — M. et 2970 — M jusqu'au vilhge de Bongomaro ; Au sud, par la concession n°1059, jusqu'au nord du village de Beilalana, puis; par une ligne droite passant par le village de Bedo et allant jusqu'à l'angle S. W. de la 7e réserve naturelle ; A l'est, par la 7e réserve naturelle.

Les articles 50 à 52 du code forestier de 1913 précisent les règles applicables aux réserves forestières :


